type ColdCountry = string;

export const coldCountries: ColdCountry[] = [
  "Canada",
  "Iceland",
  "Greenland",
  "Norway",
  "Sweden",
  "Finland",
  "Denmark",
  "Russia",
  "Estonia",
  "Latvia",
  "Lithuania",
  "United States",
  "United Kingdom",
  "Switzerland",
  "Austria",
  "Germany",
  "Poland",
  "Czech Republic",
  "Slovakia",
  "Ukraine",
  "Belarus",
  "Kazakhstan",
  "Mongolia",
  "Japan",
  "South Korea",
  "China",
];
